@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgxNTU1MjV9.V4QIJR3xvgxcUFy4XwSF2fjymAImQc8QYmUCiPiz68w

### Products index actiion
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}


### Products show action 
GET http://localhost:3000/products/5.json

### Product create action
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "TEST PRODUCT 2",
  "price": 0.99,
  "description": "THIS IS A TEST PRODUCT.",
  "supplier_id": 1
  
}

### Product update action 
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{ 
  "name": "Horizon Forbidden West",
  "price": 59.99,
  "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ3gqDNgW5cC8HC9Q9pAwo2mrnQAJ8ixliOg&usqp=CAU",
  "description": "A sequel to 2017's Horizon Zero Dawn, the game is set in a post-apocalyptic version of the Western United States recovering from the aftermath of an extinction event caused by a rogue robot swarm. The player can explore the open world and complete quests using ranged and melee against hostile machine creatures.",
  "supplier_id": 2
 
}

### Product delete action 
DELETE http://localhost:3000/products/11
Authorization: Bearer {{jwt}}

### Images create saction
POST http://localhost:3000/images.json
Content-Type: application/json

{
"product_id": 6, 
"url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-nA20vG5rJcSOYtHA0e4rMfQaJ1jfIWzlFQ&usqp=CAU"

}



### User create 
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "Krystal",
  "email": "krystal@test.com",
  "password": "bananas",
  "password_confirmation": "bananas"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "krystal@test.com",
  "password": "bananas"
}


### Orders create
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Orders show 
GET http://localhost:3000/orders/1.json
Content-Type: application/json

### Orders index
GET http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Orders delete
DELETE http://localhost:3000/orders/4.json
Content-Type: application/json


### Carted Products index
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}


### Carted Products create
POST http://localhost:3000/carted_products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
"user_id" : 1,
"product_id": 5,
"quantity" : 4, 
"status": ""

}


### Carted Products delete 
DELETE http://localhost:3000/carted_products/3.json