### Products index action
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc2Nzc2MDV9.oWMLAJ29vWAgGvHn0K_0G-s-0Z69FlIQL9dxJjFcSwM


### Products show action 
GET http://localhost:3000/products/5.json

### Product create action
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "God of War 4",
  "price": 19.99,
  "description":"Play as Kratos, a Spartan warrior who is sent by the Greek Gods to kill Ares, the god of war.",
  "supplier_id": 4
  
}

### Product update action 
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{ 
  "name": "Horizon Forbidden West",
  "price": 59.99,
  "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ3gqDNgW5cC8HC9Q9pAwo2mrnQAJ8ixliOg&usqp=CAU",
  "description": "A sequel to 2017's Horizon Zero Dawn, the game is set in a post-apocalyptic version of the Western United States recovering from the aftermath of an extinction event caused by a rogue robot swarm. The player can explore the open world and complete quests using ranged and melee against hostile machine creatures.",
  "supplier_id": 2
 
}

### Product delete action 
DELETE http://localhost:3000/products/9

### Images create saction
POST http://localhost:3000/images.json
Content-Type: application/json

{
"product_id": 6, 
"url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-nA20vG5rJcSOYtHA0e4rMfQaJ1jfIWzlFQ&usqp=CAU"

}



### User create 
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "Krystal",
  "email": "krystal@test.com",
  "password": "bananas",
  "password_confirmation": "bananas"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "krystal@test.com",
  "password": "bananas"
}